### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by JoanBalado** [gsanroma/bullseye_pipeline#1]
Hi, 

Thank you for this repo Gerdard. 

I am having one issue installing the pipeline. After installing it from source (and double-checking that all dependencies are working), I get this error message when I invoke run_bullseye_pipeline from the terminal (I am working in a Ubuntu 20 OS): 

Traceback (most recent call last):
  File "/usr/local/bin/run_bullseye_pipeline", line 11, in <module>
    load_entry_point('bullseye-pipeline==1.0.0', 'console_scripts', 'run_bullseye_pipeline')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/bullseye_pipeline-1.0.0-py3.8.egg/bullseye_pipeline/run_bullseye_pipeline.py", line 6, in <module>
    from bullseye_pipeline import create_bullseye_pipeline
ImportError: cannot import name 'create_bullseye_pipeline' from 'bullseye_pipeline' (/usr/local/lib/python3.8/dist-packages/bullseye_pipeline-1.0.0-py3.8.egg/bullseye_pipeline/__init__.py)

I went to the bullseye directory and I didn't see any "create_bullseye_pipeline.py" script (I don't know if this is the problem). 

Thank you for your help. 
P.d.: Additionally, is it possible to use python 3 instead of python 2.7?

**Comment by LuuuXG** [comment]
I met the same issue. Two modifications:

1) add `from .bullseye_pipeline import create_bullseye_pipeline` into `__init__.py`
2) change `from utils import *` to `from .utils import *` in `bullseye_pipeline.py`

can solve this problem.

But I have a problem running this package with Freesurfer 7+ version, don't know if it is related to the freesurfer version.

report Error since this node:
```
[Node] Error on "bullseye.filter_lobes" (/mnt/f/Public_dataset/ADNI_test/derivatives/bullseye/output/bullseye/_subject_ids_cvs_avg35_inMNI152/filter_lobes) 
```
